apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgCi4AMXcnKagedL0nsmz4lXTktCUxD3DGMJhryciGwJf12bAU1yfVf2K65h9G6vgsUENkuo5342EJopftqelOhKqMEmo5fOkFZz1YLy4GIWEf9h6OY8kZYjVnArD/yqWRd+AWEubkLiNgeVN4aFEo7C6XjvLvyXHs5oQcR+pT6hGk52XXt1p7tiM53qT5poacvIcqGXQU9AZtKC5nZB1PKLzZXZg4W05VXyQDxSI6A75F0RUxHZL9IEWdRkJ+Icp+A2NAdAHeLtrwB/ehUnPQlpUN76RQ+iyELKbtD6dDmO5I7+xqPbXehWP/usZPUCMwdGff7AArb/LW/eri1RI5OyL3CgYSOjdqj9pABNhKC5Zkw5aouKJEAtjHbUy92Fg9u1Fs2/FOFHPXiG7140OS7tQAW1qxYhJaKjPAOEx+UEuj3QeAaORrlJI74Uh2t613IrUxXn73ubeGdsuT+ufiQbbFG/bahXePfZKFarosWgHkrAnnsMrctoXxCf+mExqNr8spo1FuYGHScoyu/YHYHDL637jHGs1RY44J+vlXChPRMGvC9AdTm8N62MxCjzF/hK0paMXq2ph5FJZzHe/prrXHR9ubNusSzg3xR+7zhmm2s3yrYMkD1+M6zaSYM541wql341Sbd6vdTt7SHOD/GaxbRztXIh6OubJjsva7SR7fDi+JSfP+BCdbDPi4iP3xp4bBtnY7hZ3iFhL8Gvym+IIoxDSFKwj2CLW24vBEuwCvOwLAr1zCh1Po02NGjWR4YEnw+pHkMWoxPsKmVv6eyJV57LBGGJG5p4+3iIQAqAZzXfVXGx2GhKrGymA7gkjqe73rAxjWLyikqJI6egUTIOUsxKpPZTIwuw5VmJWAWg/0VzEG3juTWQGX2opIk+RCVL6SwxlQvf823ts4jGjAS5PtcryLtHqWlcf9CPJeg89RUR8Xia1/qEiZbTAHvaa+Ey8MBxcEsJJJriQd7xN+RIEGks
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

