apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCEY+s408PSOT5YWfkriVZWKNmirC68HrDikfJXOVP2Mpb1KYSb9SZUF/PUaB1zCFBK7pnS5PopqVnOobCfmvemTcYDwHZHGY0MCc0JDbkWhU7CLNhfqgN2/pAWnnXHpqJSzKvgHPwv1zKjTsPFEDzyekvZaXNHzQ+9HE1OvGE54aV+94TLS+mawaBzbdpvWMr0eWXGxGssDhdrYOYQrqjplCoMQK+uOkl/bSW1bnwlRLFwMB+Wl4JNxgb//ZUX4xm8cIq5ENgC3jVJyGavUYaPrORbfgQciR0slmDWdO5V/qE14C9+ChHnri/p7et4qMt66zDLoGpq0xaYDv9Tzt4GrPgVjwsCWZv5KL0jOyfrPAMOF8wMWRDlB5syxAP3qCTK86IXasiR9WY8FohKZKtbq898oLtnlnxmZguDeBepfg3zlYtQEazPDKJVONnBjcGhiXxD6kjUFJd0Vo/F8MzP8/zJ2K/+kapBOxN+pHrIwr75ZWEljANlFC6DmGJYWqnSdzuEOtW3FCkykWK7JUmSXgio2pxopyWB3Exq5UY3GpSz8BSGgEAqT/FOXxh4J7uXkc5UQQQPfxl4sw8bQKnTD6Txn0nQsUzMHb4SZukH+vqXTb73iL3MBAptTsMosIsBrfUpqm0VlBSCG5XGrU9jRzcTemclO+bTCqYHd7RQtN0F1l85HkRV2Grg8rXlfO60lHyAkchX5rXu9dW13WMN1X/8+TQ/UBUEFINHj3IhQq+rgqNA6wqs
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

