apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCzoppGeGVFJoqx5uFVurZ1I6IcqRAgOp3hBY5Chl862caSKjVrwa0kAEEwEV6kaXTGmzOtOMqUEpoAlv9nCt8XR5n807Kx48/wHuw/fk5bsGwP/bhQT4jC3smwWEM/48gt+1jctcUi29XOrPwNyzBEIFmitKM9OrVEzxBag99zqmKVl2+ROW2SXnc1CnZE3l3T7gAl5YsfwT1Z+VG5+k/3lqwp9RjXwPRVSV8bnFIwz/36EJ7IRUmMkz9zkvirZK/uNB2daRDe1MFgnHh4jDclcSv7fszSkhS+Et78hlQPhPuzyFkseUf7kDUQibXx8ja8tfAGaUxLWlk/pH6E4Sh5DfPSjij723l308WupjZfK1nP1a3YnzgX7zc43XVbpbRQQjQX6vVeVZ38URdpaW4/N9Zlc6oMJXNjQsGg/yll8TkF+ggbdm5yHx6BmbttkZX6CyhbYcJ8er+KyEHeptJTDaYEthC9YsK6CmJi5BIKFxK9PgkMqaBr3VaAllvpOuhsd7zHmN2/iVzsjMiDqzQN/HiFP50BJyhYuyYu41Jc9EyyvWUjgr3FkEfx7baouju6g6rnwWsKt11fK+ZleW5chLLf9HStQ73pAdfb7Wq2fou4xRyhgvHbnkV1USPTX9JaTjGX9whX/sGq1QZ1zMQ2Er7hShTinSudsLayNYvGgUEmawCn6ZrFqU2vSzDeamgAF3pzhapkVTwcrlNT29qYLUmzX7fVw0iPLujnQ6SH8x2j00v/fJiP
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

